project_id = "vvuhqqvjtozhwideqdnn"

[functions.hotmart-webhook]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.tmb-webhook]
verify_jwt = false

[functions.send-sales-summary]
verify_jwt = false
