project_id = "vvuhqqvjtozhwideqdnn"

[functions.hotmart-webhook]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.tmb-webhook]
verify_jwt = false

[functions.send-sales-summary]
verify_jwt = false

[functions.test-llm-connection]
verify_jwt = true

[functions.process-scheduled-webhooks]
verify_jwt = false

[functions.get-dollar-rate]
verify_jwt = false

[functions.log-access]
verify_jwt = false

[functions.force-logout]
verify_jwt = true

[functions.security-alert]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = false
